### ISSUE TITLE
Copying Between Environments With Entities Loaded in a Different Order (different Object Type Code)

### ISSUE THREAD

**Issue by bonomo1** [a33ik/PersonalViewChartDBTransferTool#3]
I was copying from an on-premise, v8.1 environment to a v9 cloud environment. The Object Type Codes for the custom entities are different in the on-premise vs the cloud environment based on how solutions were loaded. When using this tool, various columns in the view (layoutxml specifically) retain the object type code from on-premise. This leads to it giving an error in the cloud environment. 

I queried the userquery table and could see that a view created in the cloud has object type code that is correct with the entity metadata but the migrated had the on-premise object type code

![image](https://user-images.githubusercontent.com/32522922/59568344-fb4cd780-903e-11e9-8533-70e7331427ae.png)

![image](https://user-images.githubusercontent.com/32522922/59568328-c476c180-903e-11e9-9f70-50316c617eae.png)

Unhandled exception: 
Exception type: System.ServiceModel.FaultException`1[Microsoft.Xrm.Sdk.OrganizationServiceFault]
Message: System.Xml.XmlException: Microsoft.Crm.Metadata.EntityMetadataNotFoundException: The entity with ObjectTypeCode = 10190 was not found in the MetadataCache. MetadataCacheDetails: ProviderType=Dynamic, StandardCache=True, IsLoadedInStagedContext = False, Timestamp=20563985, MinActiveRowVersion=20563985
   at Microsoft.Crm.Metadata.DynamicMetadataCache.GetEntity(Int32 entityCode)
   at Microsoft.Crm.Application.Controls.AppGrid.set_ViewId(String value)
   at Microsoft.Crm.Core.Application.WebServices.AppGridWebServiceHandler.FillNewGrid(AppGrid appGrid, XmlDocument gridXml, String id)
   at Microsoft.Crm.Core.Application.WebServices.AppGridWebServiceHandler.Reset(String gridXml, String id, StringBuilder sbXml, StringBuilder sbHtml)
   at Microsoft.Crm.Core.Application.WebServices.AppGridWebServiceHandler.ProcessRequestInternal(HttpContext context) ---> Microsoft.Crm.Metadata.EntityMetadataNotFoundException: The entity with ObjectTypeCode = 10190 was not found in the MetadataCache. MetadataCacheDetails: ProviderType=Dynamic, StandardCache=True, IsLoadedInStagedContext = False, Timestamp=20563985, MinActiveRowVersion=20563985
   at Microsoft.Crm.Metadata.DynamicMetadataCache.GetEntity(Int32 entityCode)
   at Microsoft.Crm.Application.Controls.AppGrid.set_ViewId(String value)
   at Microsoft.Crm.Core.Application.WebServices.AppGridWebServiceHandler.FillNewGrid(AppGrid appGrid, XmlDocument gridXml, String id)
   at Microsoft.Crm.Core.Application.WebServices.AppGridWebServiceHandler.Reset(String gridXml, String id, StringBuilder sbXml, StringBuilder sbHtml)
   at Microsoft.Crm.Core.Application.WebServices.AppGridWebServiceHandler.ProcessRequestInternal(HttpContext context)
   --- End of inner exception stack trace ---
   at Microsoft.Crm.Core.Application.WebServices.AppGridWebServiceHandler.ProcessRequestInternal(HttpContext context)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously): Microsoft Dynamics CRM has experienced an error. Reference number for administrators or support: #59BF0C75Detail: 
<OrganizationServiceFault xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.microsoft.com/xrm/2011/Contracts">
  <ActivityId>38dac9fd-b2f5-4197-9218-865c5bb9fd90</ActivityId>
  <ErrorCode>-2147220970</ErrorCode>
  <ErrorDetails xmlns:d2p1="http://schemas.datacontract.org/2004/07/System.Collections.Generic" />
  <Message>System.Xml.XmlException: Microsoft.Crm.Metadata.EntityMetadataNotFoundException: The entity with ObjectTypeCode = 10190 was not found in the MetadataCache. MetadataCacheDetails: ProviderType=Dynamic, StandardCache=True, IsLoadedInStagedContext = False, Timestamp=20563985, MinActiveRowVersion=20563985
   at Microsoft.Crm.Metadata.DynamicMetadataCache.GetEntity(Int32 entityCode)
   at Microsoft.Crm.Application.Controls.AppGrid.set_ViewId(String value)
   at Microsoft.Crm.Core.Application.WebServices.AppGridWebServiceHandler.FillNewGrid(AppGrid appGrid, XmlDocument gridXml, String id)
   at Microsoft.Crm.Core.Application.WebServices.AppGridWebServiceHandler.Reset(String gridXml, String id, StringBuilder sbXml, StringBuilder sbHtml)
   at Microsoft.Crm.Core.Application.WebServices.AppGridWebServiceHandler.ProcessRequestInternal(HttpContext context) ---&gt; Microsoft.Crm.Metadata.EntityMetadataNotFoundException: The entity with ObjectTypeCode = 10190 was not found in the MetadataCache. MetadataCacheDetails: ProviderType=Dynamic, StandardCache=True, IsLoadedInStagedContext = False, Timestamp=20563985, MinActiveRowVersion=20563985
   at Microsoft.Crm.Metadata.DynamicMetadataCache.GetEntity(Int32 entityCode)
   at Microsoft.Crm.Application.Controls.AppGrid.set_ViewId(String value)
   at Microsoft.Crm.Core.Application.WebServices.AppGridWebServiceHandler.FillNewGrid(AppGrid appGrid, XmlDocument gridXml, String id)
   at Microsoft.Crm.Core.Application.WebServices.AppGridWebServiceHandler.Reset(String gridXml, String id, StringBuilder sbXml, StringBuilder sbHtml)
   at Microsoft.Crm.Core.Application.WebServices.AppGridWebServiceHandler.ProcessRequestInternal(HttpContext context)
   --- End of inner exception stack trace ---
   at Microsoft.Crm.Core.Application.WebServices.AppGridWebServiceHandler.ProcessRequestInternal(HttpContext context)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean&amp; completedSynchronously): Microsoft Dynamics CRM has experienced an error. Reference number for administrators or support: #59BF0C75</Message>
  <Timestamp>2019-06-16T18:57:53.8743417Z</Timestamp>
  <ExceptionRetriable>false</ExceptionRetriable>
  <ExceptionSource i:nil="true" />
  <InnerFault>
    <ActivityId>38dac9fd-b2f5-4197-9218-865c5bb9fd90</ActivityId>
    <ErrorCode>-2147217150</ErrorCode>
    <ErrorDetails xmlns:d3p1="http://schemas.datacontract.org/2004/07/System.Collections.Generic" />
    <Message>The entity with ObjectTypeCode = 10190 was not found in the MetadataCache. MetadataCacheDetails: ProviderType=Dynamic, StandardCache=True, IsLoadedInStagedContext = False, Timestamp=20563985, MinActiveRowVersion=20563985</Message>
    <Timestamp>2019-06-16T18:57:53.8743417Z</Timestamp>
    <ExceptionRetriable>false</ExceptionRetriable>
    <ExceptionSource i:nil="true" />
    <InnerFault i:nil="true" />
    <OriginalException i:nil="true" />
    <TraceText i:nil="true" />
  </InnerFault>
  <OriginalException i:nil="true" />
  <TraceText i:nil="true" />
</OrganizationServiceFault>

**Comment by AndrewButenko** [comment]
Hello,
Thanks for the report. I will work on fix for you.
Thanks,
Andrew

**Comment by bonomo1** [comment]
Thank you Andrew! Great tool except for this one issue, have used it
successfully in other scenarios.
