### ISSUE TITLE
Unhandled Exception Has Occurred In Your Application: Unable to Read User Password - when destination instance is SDK Login Tenant

### ISSUE THREAD

**Issue by nervousisotope** [a33ik/PersonalViewChartDBTransferTool#9]
Scenario uses two tenants with different authentication. Both tenants' connections are valid.

Tenant A: Set up with Connection Wizard
Tenant B: Set up with SDK Login Control

If Tenant A is the source and Tenant B is the destination, operation load users and teams fails with message: unable to read user password.
If Tenant B is the source and Tenant A is the destination, operation load users and teams completes successfully.

![image](https://user-images.githubusercontent.com/20524602/119817788-4be53480-bee6-11eb-9a02-5cc367ca45f7.png)
System.Exception: Unable to read user password
   at McTools.Xrm.Connection.ConnectionDetail.ConnectOnline()
   at McTools.Xrm.Connection.ConnectionDetail.GetCrmServiceClient(Boolean forceNewService)
   at AButenko.PersonalViewsDashboardsTransferTool.PvdbTransferToolPluginControl.RetrieveUsers(BackgroundWorker worked, DoWorkEventArgs args)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

**Comment by BugsOli** [comment]
Same here

**Comment by AndrewButenko** [comment]
Closing as a duplicate of #5
